name: better_protoc_plugin
version: 1.2.0
description: An opinionated, "new and improved" protobuf protoc compiler plugin used to generate Dart code with real Dart enums, message interfaces, automatic DateTime/Duration conversion, etc.
repository: https://github.com/dra11y/better_protoc_plugin

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  fixnum: ^1.0.0
  path: ^1.8.0
  protobuf: ^3.1.0
  collection: ^1.15.0

dev_dependencies:
  dart_flutter_team_lints: ^2.1.1
  matcher: ^0.12.10
  test: ^1.24.9

executables:
  protoc-gen-dart: better_protoc_plugin
